In [1]:
class Employee:
    num_employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_employees += 1

    @staticmethod
    def average_salary(employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees)

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, experience):
        super().__init__(name, family, salary, department)
        self.experience = experience

employee1 = Employee("John Doe", "Family A", 60000, "HR")
employee2 = Employee("Jane Smith", "Family B", 75000, "Finance")

fulltime_employee1 = FulltimeEmployee("Alice Johnson", "Family C", 80000, "IT", 3)
fulltime_employee2 = FulltimeEmployee("Bob Williams", "Family D", 90000, "Engineering", 5)

employees = [employee1, employee2, fulltime_employee1, fulltime_employee2]
avg_salary = Employee.average_salary(employees)

print("Total number of employees:", Employee.num_employees)
print("Average salary:", avg_salary)

Total number of employees: 4
Average salary: 76250.0


In [2]:
import numpy as np
random_vector = np.random.uniform(1, 20, size=20)
print("Original array:")
print(random_vector)

reshaped_array = random_vector.reshape(4, 5)

max_indices = np.argmax(reshaped_array, axis=1)

reshaped_array[np.arange(4), max_indices] = 0

print("\nReshaped array:")
print(reshaped_array)

Original array:
[ 7.94818332 19.04774972  4.81872563 18.61887148  9.81530951  9.65078223
  8.87348601  9.65999958 15.6848486  12.15396498  9.68875192 12.57378979
  4.82342076  5.63368273  4.0958622   6.35173845 19.02808727 19.00166019
 18.10165271  2.89336494]

Reshaped array:
[[ 7.94818332  0.          4.81872563 18.61887148  9.81530951]
 [ 9.65078223  8.87348601  9.65999958  0.         12.15396498]
 [ 9.68875192  0.          4.82342076  5.63368273  4.0958622 ]
 [ 6.35173845  0.         19.00166019 18.10165271  2.89336494]]
